//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPPhoneEntities : DbContext
    {
        public IPPhoneEntities()
            : base("name=IPPhoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallPrice> CallPrices { get; set; }
        public virtual DbSet<CallRecord> CallRecords { get; set; }
        public virtual DbSet<ChargeLevel> ChargeLevels { get; set; }
        public virtual DbSet<CompanyReport> CompanyReports { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<DepartmentReport> DepartmentReports { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<PersonReport> PersonReports { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserToken> UserTokens { get; set; }
    }
}
